### ISSUE TITLE
Favor apagar a pasta .metadata do seu projeto

### ISSUE THREAD

**Issue by acenelio** [elissandroa/crudCompletoClientes#1]
Aparentemente você abriu a pasta do projeto como um workspace do STS. Isso fez com que fosse criada uma subpasta .metadata a partir da pasta raiz do seu projeto, o que fica bem inadequado. Esta pasta não deve ser salva no seu repositório Git.

Para arrumar isto, faça o seguinte:

1) Abra seu STS definindo um novo workspace para ele (por exemplo, a pasta "mãe" da pasta do seu projeto), depois importe o projeto neste novo workspace (File -> Import -> Maven -> Existing Maven Projects). Tome o cuidado de nunca mais abrir a pasta do projeto como workspace do STS, ok?

2) Apague a subpasta .metadata que está dentro da pasta do seu projeto e faça um novo commit, e depois um novo push para o Github.

**Comment by elissandroa** [comment]
Boa tarde,  obrigado professor pelo suporte já fiz as alterações e repostei a atividade,  vou ficar bem atento e não cometer mais esse erro, obrigado.

Obter o Outlook para Android<https://aka.ms/ghei36>

________________________________
