### ISSUE TITLE
Sua classe de teste está dando erro de compilação

### ISSUE THREAD

**Issue by acenelio** [elissandroa/crudCompletoClientes#2]
Sua classe de teste está dando erro de compilação no projeto. Favor incluir a seguinte dependência no seu arquivo pom.xml para eliminar esse erro de compilação:

```
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-test</artifactId>
    <scope>test</scope>
</dependency>

```

**Comment by elissandroa** [comment]
Resolvido na época, Obrigado ao professor pela correção,
